app = "minecraft-pinger"
primary_region = "arn"

[build]

[[services]]
  internal_port = 25565
  protocol = "tcp"

  [[services.ports]]
    port = 25565

  # Hold altid mindst én maskine kørende:
  min_machines_running = 1
